function t121_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoBlock=document.getElementById('youtubeiframe'+recid);var videoParent=videoBlock?videoBlock.parentNode:null;var videoWidth=videoBlock?videoBlock.offsetWidth:0;var videoHeight=videoWidth*0.5625;if(videoBlock)videoBlock.style.height=videoHeight+'px';if(videoParent)videoParent.style.height=videoHeight+'px';var videoLazy=rec?rec.querySelector('.t-video-lazyload'):null;if(videoLazy){var iframeLazy=videoLazy.querySelector('iframe');var heightLazy=videoLazy.offsetWidth*0.5625;videoLazy.style.height=heightLazy+'px';if(iframeLazy)iframeLazy.style.height=heightLazy+'px';setTimeout(function(){videoBlock=document.getElementById('youtubeiframe'+recid);videoWidth=videoBlock?videoBlock.offsetWidth:0;if(videoBlock)videoBlock.style.height=(videoWidth*0.5625)+'px'},200)}}
function t456_setListMagin(recid,imglogo){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t456');var leftSide=menu?menu.querySelector('.t456__leftwrapper'):null;var list=menu?menu.querySelector('.t456__list'):null;var leftSideWidth=leftSide?leftSide.offsetWidth:0;if(list)list.style.marginRight=(imglogo?leftSideWidth:leftSideWidth+30)+'px'}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t456__list_item a[href=\''+url+'\'], '+'.t456__list_item a[href=\''+url+'/\'], '+'.t456__list_item a[href=\''+pathname+'\'], '+'.t456__list_item a[href=\'/'+pathname+'\'], '+'.t456__list_item a[href=\''+pathname+'/\'], '+'.t456__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t456_checkAnchorLinks(recid){if(window.innerWidth<980)return;var rec=document.getElementById('rec'+recid);var navLinks=rec?rec.querySelectorAll('.t456__list_item a[href*=\'#\']'):[];navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t456_catchScroll(navLinks)}}
function t456_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t456_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t456_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t456_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t456');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t456_updateSectionsOffsets(sections)})})}
setInterval(function(){t456_updateSectionsOffsets(sections)},5000);t456_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t456_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t456_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t456_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t456_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t456_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t456_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t456_setBg(recid){var menuBlocks=document.querySelectorAll('.t456');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t456_appearMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t456');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t456_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t456_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t456_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t456_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t456');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t456_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t456');var burger=rec.querySelector('.t456__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t456_opened')){t456_fadeOut(menu,300);burger.classList.remove('t456_opened')}else{t456_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t456_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu)menu.style.opacity='';if(menu)menu.style.display='';if(burger)burger.classList.remove('t456_opened')}},200))}
function t456_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t456_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var activeHeight=0;var isAccordionDown=!1;if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;if(target<windowScroll||accordionHeight>windowHeight){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}
function t678_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t678__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t678__fadeOut(tildaLabel,50)}},300)}else{t678__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t678__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t678__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t678__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t678__easeInOutCubic(currentTime,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t678__animateScroll(){currentTime+=increment;window.scrollTo(0,t678__easeInOutCubic(currentTime,change));if(currentTime<duration){setTimeout(t678__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t678__animateScroll()}
function t688_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t688');if(!container)return;var rows=rec.querySelectorAll('.t688__row');if(window.innerWidth>=960){for(var i=0;i<rows.length;i++){var row=rows[i];var maxHeight=0;var cols=row.querySelectorAll('.t-col:not(.t688__featured):not(.t688__inner-col)');var textWrappers=row.querySelectorAll('.t688__textwrapper');var featureds=row.querySelectorAll('.t688__featured');var colEl=row.querySelector('.t688__col');for(var j=0;j<cols.length;j++){var col=cols[j];var colText=col.querySelector('.t688__textwrapper_inner');var colTextHeight=colText.offsetHeight;if(colTextHeight>maxHeight)maxHeight=colTextHeight}
for(var j=0;j<textWrappers.length;j++){textWrappers[j].style.height=maxHeight+'px'}
if(colEl){for(var j=0;j<featureds.length;j++){var featured=featureds[j];var colStyle=getComputedStyle(colEl,null);var colPaddingTop=parseInt(colStyle.paddingTop)||0;var colPaddingBottom=parseInt(colStyle.paddingBottom)||0;var colHeight=col.clientHeight-(colPaddingTop+colPaddingBottom);featured.style.height=colHeight+'px'}}}}else{var textWrappers=rec.querySelectorAll('.t688__textwrapper');var featureds=rec.querySelectorAll('.t688__featured');var col=rec.querySelector('.t688__col');if(col){var colStyle=getComputedStyle(col,null);var colPaddingTop=parseInt(colStyle.paddingTop)||0;var colPaddingBottom=parseInt(colStyle.paddingBottom)||0;var colHeight=col.clientHeight-(colPaddingTop+colPaddingBottom);for(var i=0;i<featureds.length;i++){featureds[i].style.height=colHeight+'px'}}
for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height='auto'}}}
function t764_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderContainer=rec.querySelector('.t-slds__container');var sliderWidth=sliderContainer?sliderContainer.offsetWidth:0;var sliderPos=sliderWrapper?sliderWrapper.getAttribute('data-slider-pos'):'0';var pos=parseFloat(sliderPos);if(sliderWrapper)sliderWrapper.style.transform='translate3d(-'+(sliderWidth*pos)+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)});var currentBlock=rec.querySelector('.t764');if(currentBlock){if(typeof jQuery!=='undefined'){$('.t764').on('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}else{currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}}}
function t772_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t772__container_mobile-flex');if(!container)return;var cols=rec.querySelectorAll('.t772__col');container.addEventListener('touchstart',function(){for(var i=0;i<cols.length;i++){var col=cols[i];col.removeEventListener('touchmove',t722_touchEvent);col.addEventListener('touchmove',t722_touchEvent)}})}
function t722_touchEvent(){var allRecords=document.getElementById('allrecords');if(typeof allRecords.getAttribute('data-tilda-mode')==='undefined'){if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}}
function t823_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t823__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t823__fadeOut(tildaLabel)}},300)}else{t823__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t823__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t823__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t823__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t823__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t823__animateScroll(){currentTime+=increment;window.scrollTo(0,t823__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t823__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t823__animateScroll()}
function t849_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t849__accordion')[0];var headers=rec.querySelectorAll('.t849__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;if(element.classList.contains('t849__opened')){element.classList.remove('t849__opened');t849_accordionHide(container)}else{if(accordion==='true'){t849_accordionAllHide(headers)}
element.classList.add('t849__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px'},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t849_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t849__opened');t849_accordionHide(elementHide.nextElementSibling)}}
function t849_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}}
function t923_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t923');if(!container)return;t923_unifyHeights(recId);window.addEventListener('resize',t_throttle(function(){t923_unifyHeights(recId)}));if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t923_unifyHeights(recId)})}else{container.addEventListener('displayChanged',function(){t923_unifyHeights(recId)})}
window.addEventListener('load',function(){t923_unifyHeights(recId)})}
function t923_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t923');if(!container)return;var cols=rec.querySelectorAll('.t923__content');var maxHeight=0;for(var i=0;i<cols.length;i++){cols[i].style.height=''}
for(var i=0;i<cols.length;i++){var col=cols[i];var colText=col.querySelector('.t923__textwrapper');var colBtn=col.querySelectorAll('.t923__btn-wrapper, .t923__btntext-wrapper')[0];var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var i=0;i<cols.length;i++){cols[i].style.height=maxHeight+'px'}
t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recId)})}